[tool.poetry]
name = "basilisp-pprint"
version = "0.1.0"
description = ""
authors = ["ikappaki <ikappaki@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "basilisp_pprint", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
basilisp = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
